name: publish-release-action

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build:workflow && rm -rf dist/index.js

      # Generate changelog
      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: env.previous_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (dependabot|renovate\\[bot\\]|dependabot\\[bot\\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          show-emoji: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          files: dist/**
